CREATE SCHEMA PROJETOFINAL;

USE PROJETOFINAL;

CREATE TABLE ENDERECO
(
	ID_ENDERECO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CEP CHAR(8) NOT NULL,
    LOGRADOURO VARCHAR(45) NOT NULL,
    BAIRRO VARCHAR(45) NOT NULL,
    CIDADE VARCHAR(45) NOT NULL,
    COMPLEMENTO VARCHAR(45) NOT NULL
);

CREATE TABLE SERVICO
(
	ID_SERVICO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TIPO VARCHAR(45) NOT NULL,
    DESCRICAO VARCHAR(45) NOT NULL,
    PRECO DECIMAL(6,2) NOT NULL CHECK (PRECO > 0)
);

CREATE TABLE STATUS_SERVICO
(
	ID_STATUS INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(45) NOT NULL UNIQUE
);

CREATE TABLE METODO_PAGAMENTO
(
	ID_METODO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TIPO VARCHAR(45) NOT NULL UNIQUE
);

CREATE TABLE TELEFONE
(
	ID_TELEFONE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DDD CHAR(3) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    DESCRICAO VARCHAR(45) NOT NULL
);

CREATE TABLE PET
(
	ID_PET INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(45) NOT NULL,
    ESPECIE VARCHAR(45) NOT NULL,
    RACA VARCHAR(45) NOT NULL,
    PORTE VARCHAR(45) NOT NULL
);

CREATE TABLE DONO 
(
	CPF CHAR(11) NOT NULL PRIMARY KEY,
    NOME VARCHAR(45) NOT NULL,
    EMAIL VARCHAR(45) NOT NULL UNIQUE, 
    ID_ENDERECO INT,
    FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO(ID_ENDERECO)
);

CREATE TABLE REGISTRO_SERVICO
(
	ID_REGISTRO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DATA_REGISTRO DATE NOT NULL,
    HORARIO time NOT NULL,
    CPF_DONO CHAR(11) NOT NULL,
    ID_PET INT NOT NULL,
    ID_STATUS INT NOT NULL, 
    ID_SERVICO INT NOT NULL,
    FOREIGN KEY (CPF_DONO) REFERENCES DONO(CPF),
    FOREIGN KEY (ID_PET) REFERENCES PET(ID_PET),
    FOREIGN KEY (ID_STATUS) REFERENCES STATUS_SERVICO(ID_STATUS),
    FOREIGN KEY (ID_SERVICO) REFERENCES SERVICO(ID_SERVICO)
);

CREATE TABLE COMANDA
(
	ID_COMANDA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	PRECO_TOTAL DECIMAL(6,2) NOT NULL CHECK (PRECO_TOTAL > 0),
    ID_METODO INT,
    ID_REGISTRO INT NOT NULL UNIQUE,
    FOREIGN KEY (ID_METODO) REFERENCES METODO_PAGAMENTO(ID_METODO),
    FOREIGN KEY (ID_REGISTRO) REFERENCES REGISTRO_SERVICO(ID_REGISTRO)
);

CREATE TABLE DONO_TELEFONE
(
	CPF_DONO CHAR(11) NOT NULL,
    ID_TELEFONE INT NOT NULL,
    PRIMARY KEY (CPF_DONO, ID_TELEFONE),
    FOREIGN KEY (CPF_DONO) REFERENCES DONO(CPF),
    FOREIGN KEY (ID_TELEFONE) REFERENCES TELEFONE(ID_TELEFONE)
);

CREATE TABLE DONO_PET
(
	CPF_DONO CHAR(11) NOT NULL,
    ID_PET INT NOT NULL,
    PRIMARY KEY (CPF_DONO, ID_PET),
    FOREIGN KEY (CPF_DONO) REFERENCES DONO(CPF),
    FOREIGN KEY (ID_PET) REFERENCES PET(ID_PET)
);

CREATE VIEW CLIENTE_PET AS
SELECT 
	D.CPF AS 'CPF Dono',
    D.NOME AS 'Dono',
    D.EMAIL AS 'E-mail',
    P.ID_PET AS 'ID Pet',
    P.NOME AS 'Nome do pet',
    P.ESPECIE AS 'Espécie',
    P.RACA AS 'Raça',
    P.PORTE AS 'Porte'
FROM DONO D
JOIN DONO_PET DP ON D.CPF = DP.CPF_DONO
JOIN PET P ON DP.ID_PET = P.ID_PET; 

SELECT * FROM CLIENTE_PET WHERE DONO LIKE '%Juliana%';

CREATE VIEW MAIS_VENDIDOS AS 
SELECT 
	S.TIPO AS 'Serviço',
    COUNT(RS.ID_REGISTRO) AS 'Quantidade de vezes vendido',
    SUM(C.PRECO_TOTAL) AS 'Faturamento total'
FROM SERVICO S
LEFT JOIN REGISTRO_SERVICO RS ON S.ID_SERVICO = RS.ID_SERVICO
LEFT JOIN COMANDA C ON RS.ID_REGISTRO = C.ID_REGISTRO
GROUP BY S.ID_SERVICO, S.TIPO; 

SELECT * FROM MAIS_VENDIDOS ORDER BY `Faturamento total` DESC; 